name: Feature request
description: Record a proposed internal enhancement
title: "[feat]: "
labels: ["enhancement"]
body:
  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: What problem are you trying to solve? Why is this important?
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: Describe the feature and, if possible, the API you have in mind.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
    validations:
      required: false

  - type: textarea
    id: extra
    attributes:
      label: Additional context
    validations:
      required: false
